### PR TITLE
Implement dragging event with universal function

### PR DESCRIPTION
**Pull request by nikischin**

### CODE REVIEW

**Review by Nicolapps — APPROVED** [review]
Thank you for the PR!

**Comment by Nicolapps** [comment]
This change was published in the latest release, mapkit-react 1.12.0.

**Comment by nikischin** [comment]
Thank you so much @Nicolapps! Also thank you for your code improvements! Talking about the editor settings, I remember you told me something about it already, could you possibly also add to the readme how to set up the configuration? I am used to eslint, but looks like you require some additional code validation? :)

**Comment by Nicolapps** [comment]
Thank you for the suggestion! I updated the README, and also updated the CI so that it runs EditorConfig automatically.

The ESLint configuration is coherent with the EditorConfig settings that are used in this repository, but ESLint only checks JavaScript/TypeScript files. With the new setup, it should be more convenient.

**Pull request merged**
